# Welcome to Ultimate Jekyll!
# This is the default configuration file for your project.

# Site configurations
url: ""
baseurl: ""

# Project
version: '1.0.0'
app: ''

# Meta
meta:
  title: ""
  description: ""
  og-images: "https://cdn.itwcreativeworks.com/assets/itw-creative-works/images/socials/itw-creative-works-brandmark-square-black-1024x1024.png"
  keywords: ""
  viewport: ""
  index: true
  referrer: ""

# Brand
brand:
  name: ""
  type: "Corporation"
  description: "."
  logo-images: "https://cdn.itwcreativeworks.com/assets/itw-creative-works/images/logo/itw-creative-works-brandmark-black-1024x1024.png"
  logo-image-svg: "https://cdn.itwcreativeworks.com/assets/itw-creative-works/images/logo/itw-creative-works-brandmark-black-x.svg"
  address-locality: "Los Angeles"
  address-country: "United States"

# Favicon
favicon:
  path: "https://cdn.itwcreativeworks.com/assets/itw-creative-works/images/favicon"
  safari-pinned-tab: "#5bbad5"
  msapp-tile-color: "#da532c"
  theme-color: "#ffffff"

# Socials
socials:
  facebook: ""
  twitter: ""
  linkedin: ""
  youtube: ""
  instagram: ""
  tumblr: ""
  slack: ""
  discord: ""
  github: ""
  dev: ""
  tiktok: ""
  twitch: ""
  soundcloud: ""
  spotify: ""
  mixcloud: ""

# Cloudflare
cloudflare:
  zone: ""

# Tracking
tracking:
  google-analytics: false
  facebook-pixel: false
  tiktok-pixel: false

# Contact
contact:
  email-support: ""
  email-business: ""
  slapform-form-id: ""
  phone: ""

# Manifest
manifest:
  name: ""
  short-name: ""
  theme-color: "#ffffff"
  background-color: "#ffffff"
  display: "standalone"
  start-url: "/?source=pwa"
  scope: "/"
  orientation: "portrait"

# Download
download:
  mac: ""
  windows: ""
  linux-debian: ""
  linux-snap: ""
  ios: ""
  android: ""

# Extension
extension:
  chrome: ""
  firefox: ""
  opera: ""
  safari: ""
  edge: ""

# Site settings
settings:
  include-app-head: true
  include-app-foot: true
  include-script-bundle: true
  include-script-bundle-optimization: "async"
  include-script-core: false
  include-script-core-optimization: "async"
  include-script-slapform: false
  include-script-slapform-optimization: "async"
  include-css-bundle: true
  include-css-normalize: false
  include-css-reset: false
  include-css-defaults: true
  include-html5shiv: true
  include-socialsharekit: true
  include-debug-performance: false
  blog-post-image-class: ""
  blog-author-image-class: ""
  manager-configuration: "
    {
      libraries: {
        firebase_app: {
          enabled: true,
          config: {
            apiKey: '',
            authDomain: '',
            databaseURL: '',
            projectId: '',
            storageBucket: '',
            messagingSenderId: '',
            appId: '',
            measurementId: '',
          },
        },
        firebase_appCheck: {
          enabled: false,
          config: {
            siteKey: '',
          },
        },
        cookieconsent: {
          enabled: true,
          config: {
            palette: {
              popup: {
                background: '#fd5631',
                text: '#fff',
              },
              button: {
                background: '#fff',
                text: '#fd5631',
              },
            },
          },
        },
        chatsy: {
          enabled: true,
          config: {
            accountId: '',
            chatId: '',
            settings: {
              openChatButton: {
                background: '#fd5631',
                text: '#fff',
              },
            },
          },
        },
        sentry: {
          enabled: true,
          config: {
            dsn: '',
            release: '',
            replaysSessionSampleRate: 0.01,
            replaysOnErrorSampleRate: 0.01,
          },
        },
      },
      exitPopup: {
        enabled: true,
        config: {
          timeout: 1000 * 60 * 60 * 4,
          handler: null,
          title: 'Want 50% off your gift?',
          messages: 'There are some gifts on sale today for as much as 50% off. Click the button below to claim your discount!',
          okButton: {
            text: 'Claim 50% Discount',
            link: 'https://giftly.app',
          },
        },
      },
    }
  "

# Custom admin dashboard pages
admin-dashboard: "{
  pages: [
  ]
}"

# Schema
schema:
  breadcrumbs: true
  brand: true
  sitelinks: true

# Search
search:
  enable: true

# Sitemap
sitemap:
  enable: true

# Blog & Pagination
permalink: /blog/:title
pagination:
  enabled: true
  per_pages: 6
  offset: 0
  limit: 0
  permalink: /page/:num.html
  title: :title - page :num
  sort_field: 'date'
  sort_reverse: true

# Jekyll collections
collections:
  team:
    title: Team Members
    output: true

# Jekyll defaults
defaults:
- scope:
    path: ''
    type: team
  values:
    permalink: /team/:title
